services:
  # ------------------------------------------------------
  # accomodation service 
  accommodation-service:
    build:
      context: ./services/accommodation-service
    ports:
      - "${ACCOMODATION_SERVICE_PORT}:3000"
    environment:
      - NODE_ENV=${NODE_ENV}
      - DB_CONNECTION_STRING=${DB_CONNECTION_STRING}
      - DB_APP_NAME=${DB_APP_NAME}
      - DB_DEVELOPMENT=${DB_DEVELOPMENT}
      - DB_TESTING=${DB_TESTING}
      - DB_PRODUCTION=${DB_PRODUCTION}
    volumes:
      - ./services/accommodation-service:/usr/src/app
      - /usr/src/app/node_modules
  # ------------------------------------------------------
  # activitiy service 
  activity-service:
    build:
      context: ./services/activities-service
    ports:
      - "${ACTIVITY_SERVICE_PORT}:3000"
    environment:
      - NODE_ENV=${NODE_ENV}
      - DB_CONNECTION_STRING=${DB_CONNECTION_STRING}
      - DB_APP_NAME=${DB_APP_NAME}
      - DB_DEVELOPMENT=${DB_DEVELOPMENT}
      - DB_TESTING=${DB_TESTING}
      - DB_PRODUCTION=${DB_PRODUCTION}
    volumes:
      - ./services/activities-service:/usr/src/app
      - /usr/src/app/node_modules    
  # ------------------------------------------------------
  # api gateway 
  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - "${API_GATEWAY_PORT}:8080"
    depends_on:
      - accommodation-service
    environment:
      - NODE_ENV=${NODE_ENV}
      - DB_CONNECTION_STRING=${DB_CONNECTION_STRING}
      - DB_APP_NAME=${DB_APP_NAME}
      - DB_DEVELOPMENT=${DB_DEVELOPMENT}
      - DB_TESTING=${DB_TESTING}
      - DB_PRODUCTION=${DB_PRODUCTION}
    volumes:
      - ./api-gateway:/usr/src/app
      - /usr/src/app/node_modules  
